name: Python CI checks

on: [pull_request]

jobs:
  build:
    name: CI checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Lint
      run: pylint --reports=no setup.py pockette/ tests/
    - name: Type check
      run: mypy setup.py pockette/ tests/
    - name: Test
      run: pytest --cov-report term-missing --cov=pockette/ tests
